agencyentity:
    pattern:  /
    defaults: { _controller: "HotelreserveBundle:agencyEntity:index" }

agencyentity_show:
    pattern:  /{id}/show
    defaults: { _controller: "HotelreserveBundle:agencyEntity:show" }

agencyentity_new:
    pattern:  /new
    defaults: { _controller: "HotelreserveBundle:agencyEntity:new" }

agencyentity_create:
    pattern:  /create
    defaults: { _controller: "HotelreserveBundle:agencyEntity:create" }
    requirements: { _method: post }

agencyentity_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "HotelreserveBundle:agencyEntity:edit" }

agencyentity_update:
    pattern:  /{id}/update
    defaults: { _controller: "HotelreserveBundle:agencyEntity:update" }
    requirements: { _method: post|put }

agencyentity_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "HotelreserveBundle:agencyEntity:delete" }
    requirements: { _method: post|delete }
