blankentity:
    pattern:  /
    defaults: { _controller: "HotelreserveBundle:blankEntity:index" }

blankentity_show:
    pattern:  /{id}/show
    defaults: { _controller: "HotelreserveBundle:blankEntity:show" }

blankentity_new:
    pattern:  /new
    defaults: { _controller: "HotelreserveBundle:blankEntity:new" }

blankentity_create:
    pattern:  /create
    defaults: { _controller: "HotelreserveBundle:blankEntity:create" }
    requirements: { _method: post }

blankentity_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "HotelreserveBundle:blankEntity:edit" }

blankentity_update:
    pattern:  /{id}/update
    defaults: { _controller: "HotelreserveBundle:blankEntity:update" }
    requirements: { _method: post|put }

blankentity_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "HotelreserveBundle:blankEntity:delete" }
    requirements: { _method: post|delete }
