customer:
    pattern:  /
    defaults: { _controller: "HotelreserveBundle:customerEntity:index" }

customer_show:
    pattern:  /{id}/show
    defaults: { _controller: "HotelreserveBundle:customerEntity:show" }

customer_new:
    pattern:  /new
    defaults: { _controller: "HotelreserveBundle:customerEntity:new" }

customer_create:
    pattern:  /create
    defaults: { _controller: "HotelreserveBundle:customerEntity:create" }
    requirements: { _method: post }

customer_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "HotelreserveBundle:customerEntity:edit" }

customer_update:
    pattern:  /{id}/update
    defaults: { _controller: "HotelreserveBundle:customerEntity:update" }
    requirements: { _method: post|put }

customer_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "HotelreserveBundle:customerEntity:delete" }
    requirements: { _method: post|delete }
