customerentity:
    pattern:  /
    defaults: { _controller: "HotelreserveBundle:customerEntity:index" }

customerentity_show:
    pattern:  /{id}/show
    defaults: { _controller: "HotelreserveBundle:customerEntity:show" }

customerentity_new:
    pattern:  /new
    defaults: { _controller: "HotelreserveBundle:customerEntity:new" }

customerentity_create:
    pattern:  /create
    defaults: { _controller: "HotelreserveBundle:customerEntity:create" }
    requirements: { _method: post }

customerentity_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "HotelreserveBundle:customerEntity:edit" }

customerentity_update:
    pattern:  /{id}/update
    defaults: { _controller: "HotelreserveBundle:customerEntity:update" }
    requirements: { _method: post|put }

customerentity_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "HotelreserveBundle:customerEntity:delete" }
    requirements: { _method: post|delete }
