hotelentity:
    pattern:  /
    defaults: { _controller: "HotelreserveBundle:hotelEntity:index" }

hotelentity_show:
    pattern:  /{id}/show
    defaults: { _controller: "HotelreserveBundle:hotelEntity:show" }

hotelentity_new:
    pattern:  /new
    defaults: { _controller: "HotelreserveBundle:hotelEntity:new" }

hotelentity_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "HotelreserveBundle:hotelEntity:edit" }