masterentity:
    pattern:  /
    defaults: { _controller: "HotelreserveBundle:masterEntity:index" }

masterentity_show:
    pattern:  /{id}/show
    defaults: { _controller: "HotelreserveBundle:masterEntity:show" }

masterentity_new:
    pattern:  /new
    defaults: { _controller: "HotelreserveBundle:masterEntity:new" }

masterentity_create:
    pattern:  /create
    defaults: { _controller: "HotelreserveBundle:masterEntity:create" }
    requirements: { _method: post }

masterentity_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "HotelreserveBundle:masterEntity:edit" }

masterentity_update:
    pattern:  /{id}/update
    defaults: { _controller: "HotelreserveBundle:masterEntity:update" }
    requirements: { _method: post|put }

masterentity_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "HotelreserveBundle:masterEntity:delete" }
    requirements: { _method: post|delete }
