moneyentity:
    pattern:  /
    defaults: { _controller: "HotelreserveBundle:moneyEntity:index" }

moneyentity_new:
    pattern:  /new
    defaults: { _controller: "HotelreserveBundle:moneyEntity:new" }

moneyentity_create:
    pattern:  /create
    defaults: { _controller: "HotelreserveBundle:moneyEntity:create" }
    requirements: { _method: post }

moneyentity_accept:
    pattern:  /accept/{id}
    defaults: { _controller: "HotelreserveBundle:moneyEntity:accept" }

moneyentity_reject:
    pattern:  /reject/{id}
    defaults: { _controller: "HotelreserveBundle:moneyEntity:reject" }

moneyentity_delete:
    pattern:  /delete/{id}
    defaults: { _controller: "HotelreserveBundle:moneyEntity:delete" }