reserve:
    pattern:  /
    defaults: { _controller: "HotelreserveBundle:reserveEntity:index" }

reserve_show:
    pattern:  /{id}/show
    defaults: { _controller: "HotelreserveBundle:reserveEntity:show" }

reserve_new:
    pattern:  /new
    defaults: { _controller: "HotelreserveBundle:reserveEntity:new" }

reserve_create:
    pattern:  /create
    defaults: { _controller: "HotelreserveBundle:reserveEntity:create" }
    requirements: { _method: post }

reserve_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "HotelreserveBundle:reserveEntity:edit" }

reserve_update:
    pattern:  /{id}/update
    defaults: { _controller: "HotelreserveBundle:reserveEntity:update" }
    requirements: { _method: post|put }

reserve_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "HotelreserveBundle:reserveEntity:delete" }
    requirements: { _method: post|delete }
