reserveentity:
    pattern:  /
    defaults: { _controller: "HotelreserveBundle:reserveEntity:index" }

reserveentity_show:
    pattern:  /{id}/show
    defaults: { _controller: "HotelreserveBundle:reserveEntity:show" }

reserveentity_new:
    pattern:  /new
    defaults: { _controller: "HotelreserveBundle:reserveEntity:new" }

reserveentity_create:
    pattern:  /create
    defaults: { _controller: "HotelreserveBundle:reserveEntity:create" }
    requirements: { _method: post }

reserveentity_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "HotelreserveBundle:reserveEntity:edit" }

reserveentity_update:
    pattern:  /{id}/update
    defaults: { _controller: "HotelreserveBundle:reserveEntity:update" }
    requirements: { _method: post|put }

reserveentity_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "HotelreserveBundle:reserveEntity:delete" }
    requirements: { _method: post|delete }
