roomentity:
    pattern:  /
    defaults: { _controller: "HotelreserveBundle:roomEntity:index" }

roomentity_new:
    pattern:  /new
    defaults: { _controller: "HotelreserveBundle:roomEntity:new" }

roomentity_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "HotelreserveBundle:roomEntity:edit" }

roomentity_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "HotelreserveBundle:roomEntity:delete" }
