userentity:
    pattern:  /
    defaults: { _controller: "HotelreserveBundle:userEntity:index" }

userentity_show:
    pattern:  /{id}/show
    defaults: { _controller: "HotelreserveBundle:userEntity:show" }

userentity_new:
    pattern:  /new
    defaults: { _controller: "HotelreserveBundle:userEntity:new" }

userentity_create:
    pattern:  /create
    defaults: { _controller: "HotelreserveBundle:userEntity:create" }
    requirements: { _method: post }

userentity_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "HotelreserveBundle:userEntity:edit" }

userentity_update:
    pattern:  /{id}/update
    defaults: { _controller: "HotelreserveBundle:userEntity:update" }
    requirements: { _method: post|put }

userentity_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "HotelreserveBundle:userEntity:delete" }
    requirements: { _method: post|delete }
