g_main:
    pattern:  /
    defaults: { _controller: HotelreserveBundle:Agency:home }
g_Rool_Account:
    pattern:  /rollaccount
    defaults: { _controller: HotelreserveBundle:accountEntity:AgencyIndex }