main:
    pattern:  /
    defaults: { _controller: HotelreserveBundle:Default:main }
admin:
    resource: "@HotelreserveBundle/Resources/config/admin.yml"
    prefix:   /admin
hoteldar:
    resource: "@HotelreserveBundle/Resources/config/hoteldar.yml"
    prefix:   /hoteldar
reserve:
    resource: "@HotelreserveBundle/Resources/config/agency.yml"
    prefix:   /agency
HotelreserveBundle_accountentity:
    resource: "@HotelreserveBundle/Resources/config/routing/accountentity.yml"
    prefix:   /accountentity
HotelreserveBundle_agencyentity:
    resource: "@HotelreserveBundle/Resources/config/routing/agencyentity.yml"
    prefix:   /agencyentity
HotelreserveBundle_blankentity:
    resource: "@HotelreserveBundle/Resources/config/routing/blankentity.yml"
    prefix:   /blankentity
HotelreserveBundle_customerentity:
    resource: "@HotelreserveBundle/Resources/config/routing/customerentity.yml"
    prefix:   /customerentity
HotelreserveBundle_hotelentity:
    resource: "@HotelreserveBundle/Resources/config/routing/hotelentity.yml"
    prefix:   /admin/addhotel
HotelreserveBundle_masterentity:
    resource: "@HotelreserveBundle/Resources/config/routing/masterentity.yml"
    prefix:   /masterentity
HotelreserveBundle_reserveentity:
    resource: "@HotelreserveBundle/Resources/config/routing/reserveentity.yml"
    prefix:   /reserveentity
HotelreserveBundle_roomentity:
    resource: "@HotelreserveBundle/Resources/config/routing/roomentity.yml"
    prefix:   /roomentity
HotelreserveBundle_userentity:
    resource: "@HotelreserveBundle/Resources/config/routing/userentity.yml"
    prefix:   /admin/userentity
Hotelregister_register:
    resource: "@HotelreserveBundle/Resources/config/routing/register.yml"
    prefix:   /admin/registering
hotelreserve_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: HotelreserveBundle:Default:index }