admin:
    resource: "@HotelreserveBundle/Resources/config/admin/admin.yml"
    prefix:   /admin

hoteldar:
    resource: "@HotelreserveBundle/Resources/config/hotel/hoteldar.yml"
    prefix:   /hoteldar

reserve:
    resource: "@HotelreserveBundle/Resources/config/agency/agency.yml"
    prefix:   /agency


HotelreserveBundle_bankentity:
    resource: "@HotelreserveBundle/Resources/config/routing/bankentity.yml"
    prefix:   /agency/bankentity
HotelreserveBundle_moneyentity:
    resource: "@HotelreserveBundle/Resources/config/routing/moneyentity.yml"
    prefix:   /moneyentity

login_page:
    pattern:  /
    defaults: { _controller: FOSUserBundle:Security:login }

Hotelreserve_service:
    pattern:  /hotelService
    defaults: { _controller: "HotelreserveBundle:Service:index" }

Hotelreserve_test:
    pattern:  /servicetest
    defaults: { _controller: "HotelreserveBundle:Service:get" }