admin:
    resource: "@HotelreserveBundle/Resources/config/admin/admin.yml"
    prefix:   /admin

hoteldar:
    resource: "@HotelreserveBundle/Resources/config/hotel/hoteldar.yml"
    prefix:   /hoteldar

reserve:
    resource: "@HotelreserveBundle/Resources/config/agency/agency.yml"
    prefix:   /agency


HotelreserveBundle_accountentity:
    resource: "@HotelreserveBundle/Resources/config/routing/accountentity.yml"
    prefix:   /accountentity
HotelreserveBundle_agencyentity:
    resource: "@HotelreserveBundle/Resources/config/routing/agencyentity.yml"
    prefix:   /agencyentity
HotelreserveBundle_bankentity:
    resource: "@HotelreserveBundle/Resources/config/routing/bankentity.yml"
    prefix:   /agency/bankentity
HotelreserveBundle_blankentity:
    resource: "@HotelreserveBundle/Resources/config/routing/blankentity.yml"
    prefix:   /blankentity
HotelreserveBundle_customerentity:
    resource: "@HotelreserveBundle/Resources/config/routing/customerentity.yml"
    prefix:   /customerentity
HotelreserveBundle_moneyentity:
    resource: "@HotelreserveBundle/Resources/config/routing/moneyentity.yml"
    prefix:   /moneyentity
HotelreserveBundle_masterentity:
    resource: "@HotelreserveBundle/Resources/config/routing/masterentity.yml"
    prefix:   /masterentity
HotelreserveBundle_reserveentity:
    resource: "@HotelreserveBundle/Resources/config/routing/reserveentity.yml"
    prefix:   /reserveentity
HotelreserveBundle_userentity:
    resource: "@HotelreserveBundle/Resources/config/routing/userentity.yml"
    prefix:   /admin/userentity
Hotelregister_register:
    resource: "@HotelreserveBundle/Resources/config/routing/register.yml"
    prefix:   /admin/registering

monitoring:
    pattern:  /monitoring
    defaults: { _controller: HotelreserveBundle:Default:index }

monitoring_edit:
    pattern:  /monitoring/{hotelid}/{year}/{month}/edit
    defaults: { _controller: HotelreserveBundle:Default:edit }

login_page:
    pattern:  /
    defaults: { _controller: FOSUserBundle:Security:login }

Hotelreserve_service:
    pattern:  /hotelService
    defaults: { _controller: "HotelreserveBundle:Service:index" }

Hotelreserve_test:
    pattern:  /servicetest
    defaults: { _controller: "HotelreserveBundle:Service:get" }