parameters:
#    assets.example.class: Hotel\reserveBundle\Example

services:
#    assets.example:
#        class: %assets.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
