parameters:
#    assets.example.class: Hotel\reserveBundle\Example

services:
#    assets.example:
#        class: %assets.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     authentication_handler:
         class: Hotel\reserveBundle\Handler\AuthenticationHandler
         arguments: [@router, @security.context]

     hotel_user.registration.form.type:
        class: Hotel\reserveBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: hotel_user_registration }