parameters:
#    assets.example.class: Hotel\reserveBundle\Example

services:
#    assets.example:
#        class: %assets.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    authentication_handler:
        class: Hotel\reserveBundle\Handler\AuthenticationHandler
        arguments: [@router, @security.context]

    hotel_user.registration.form.type:
        class: Hotel\reserveBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: hotel_user_registration }

    my_date_convert:
        class: Hotel\reserveBundle\Handler\DateConvertor
        arguments: [@ce.jalali_date.date_converter]

    hotel_user.form.type.ShamsiDate:
        class: Hotel\reserveBundle\Form\Type\ShamsiDateType
        tags:
            - { name: form.type, alias: shamsi_date }
        arguments: [@my_date_convert]

    hotel_service:
        class: Hotel\reserveBundle\Service\HotelService
        arguments: [@my_date_convert,@doctrine.orm.entity_manager,@security.encoder_factory]