Hotel\reserveBundle\Entity\userEntity:
    properties:
        user_firstname:
            - NotBlank:
                message: "فیلد نمیتواند خالی باشد"
            - Length:
                min: 2
                max: 50
                minMessage: 'حداقل کاراکتر رعایت نشده'
                maxMessage: 'حداکثر کاراکتر رعایت نشده'
        user_family:
            - NotBlank:
                message: "فیلد نمیتواند خالی باشد"
            - Length:
                min: 2
                max: 50
                minMessage: 'حداقل کاراکتر رعایت نشده'
                maxMessage: 'حداکثر کاراکتر رعایت نشده'
        user_city:
            - NotBlank:
                message: "فیلد نمیتواند خالی باشد"
            - Length:
                min: 2
                max: 50
                minMessage: 'حداقل کاراکتر رعایت نشده'
                maxMessage: 'حداکثر کاراکتر رعایت نشده'
        user_nameBank:
            - NotBlank:
                message: "فیلد نمیتواند خالی باشد"
            - Length:
                min: 2
                max: 40
                minMessage: 'حداقل کاراکتر رعایت نشده'
                maxMessage: 'حداکثر کاراکتر رعایت نشده'

Hotel\reserveBundle\Entity\hotelEntity:
    properties:
        hotel_name:
            - NotBlank:
                message: "فیلد نمیتواند خالی باشد"
            - Length:
                min: 2
                max: 50
                minMessage: 'حداقل کاراکتر رعایت نشده'
                maxMessage: 'حداکثر کاراکتر رعایت نشده'
        hotel_manageName:
            - NotBlank:
                message: "فیلد نمیتواند خالی باشد"
            - Length:
                min: 2
                max: 50
                minMessage: 'حداقل کاراکتر رعایت نشده'
                maxMessage: 'حداکثر کاراکتر رعایت نشده'
        hotel_grade:
            - NotBlank:
                message: "فیلد نمیتواند خالی باشد"
            - Length:
                min: 1
                max: 22
                minMessage: 'حداقل کاراکتر رعایت نشده'
                maxMessage: 'حداکثر کاراکتر رعایت نشده'
        hotel_city:
            - NotBlank:
                message: "فیلد نمیتواند خالی باشد"
            - Length:
                min: 2
                max: 50
                minMessage: 'حداقل کاراکتر رعایت نشده'
                maxMessage: 'حداکثر کاراکتر رعایت نشده'
        hotel_email:
            - NotBlank:
                message: "فیلد نمیتواند خالی باشد"
            - Length:
                min: 2
                max: 50
                minMessage: 'حداقل کاراکتر رعایت نشده'
                maxMessage: 'حداکثر کاراکتر رعایت نشده'

Hotel\reserveBundle\Entity\roomEntity:
    properties:
        room_name:
            - NotBlank:
                message: "فیلد نمیتواند خالی باشد"
            - Length:
                min: 2
                max: 50
                minMessage: 'حداقل کاراکتر رعایت نشده'
                maxMessage: 'حداکثر کاراکتر رعایت نشده'
        room_capacity:
            - NotBlank:
                message: "فیلد نمیتواند خالی باشد"
            - Length:
                min: 1
                max: 4
                minMessage: 'حداقل کاراکتر رعایت نشده'
                maxMessage: 'حداکثر کاراکتر رعایت نشده'
            - Type:
                type: integer
                message: "این مقدار معتبر نیست"
        room_addCapacity:
            - NotBlank:
                message: "فیلد نمیتواند خالی باشد"
            - Length:
                min: 1
                max: 3
                minMessage: 'حداقل کاراکتر رعایت نشده'
                maxMessage: 'حداکثر کاراکتر رعایت نشده'
            - Type:
                type: integer
                message: "این مقدار معتبر نیست"
