hotel_monitoring_index:
    pattern:  /
    defaults: { _controller: HotelreserveBundle:HotelMonitoring:index }

hotel_monitoring_edit:
    pattern:  /{hotelid}/{month}/{year}/edit
    defaults: { _controller: HotelreserveBundle:HotelMonitoring:edit }