hotel_reporting_financial_accounts:
    pattern:  /financialAccounts
    defaults: { _controller: HotelreserveBundle:HotelReporting:financialAccounts }

hotel_reporting_reserving_of_hotels:
    pattern:  /reservingOfHotels
    defaults: { _controller: HotelreserveBundle:HotelReporting:reservingOfHotels }

hotel_reporting_reserving_of_hotels_show:
    pattern:  /reservingOfHotels/{id}/show
    defaults: { _controller: HotelreserveBundle:HotelReporting:reservingOfHotelsShow }

hotel_reporting_list_hotel_by_city:
    pattern:  /listHotelByCity
    defaults: { _controller: HotelreserveBundle:HotelReporting:listHotelByCity }