a_main:
    pattern:  /
    defaults: { _controller: HotelreserveBundle:Admin:admin }

admin_hotel:
    resource: "@HotelreserveBundle/Resources/config/admin/hotelentity.yml"
    prefix:   /hotel

admin_room:
    resource: "@HotelreserveBundle/Resources/config/admin/roomentity.yml"
    prefix:   /hotel/{hotel_id}/room

admin_monitoring:
    resource: "@HotelreserveBundle/Resources/config/admin/monitoring.yml"
    prefix:   /monitoring

admin_user:
    resource: "@HotelreserveBundle/Resources/config/admin/user.yml"
    prefix:   /user

admin_agency:
    resource: "@HotelreserveBundle/Resources/config/admin/agency.yml"
    prefix:   /agency

admin_reporting:
    resource: "@HotelreserveBundle/Resources/config/admin/reporting.yml"
    prefix:   /reporting

admin_customer:
    resource: "@HotelreserveBundle/Resources/config/admin/customer.yml"
    prefix:   /customer