g_main:
    pattern:  /
    defaults: { _controller: HotelreserveBundle:Agency:home }
g_moneyentity:
    pattern:  /gmoney
    defaults: { _controller: "HotelreserveBundle:moneyEntity:index" }
g_payment:
    pattern:  /gpayment
    defaults: { _controller: HotelreserveBundle:Default:payment }

agency_reporting:
    resource: "@HotelreserveBundle/Resources/config/agency/reporting.yml"
    prefix:   /reporting