g_main:
    pattern:  /
    defaults: { _controller: HotelreserveBundle:Agency:home }

agency_reporting:
    resource: "@HotelreserveBundle/Resources/config/agency/reporting.yml"
    prefix:   /reporting

agency_money:
    resource: "@HotelreserveBundle/Resources/config/agency/money.yml"
    prefix:   /money